### ISSUE TITLE
请问对于第三方依赖的绝对路径引入是如何处理的呢？

### ISSUE THREAD

**Issue by sanyuan0704** [ltaoo/umi-preset-vite#1]
.umi 目录中的文件对于第三方库的引入都是通过绝对路径，但 vite 并不会对这些库进行预构建，请问这里处理的思路是什么呢？

**Comment by ltaoo** [comment]
通过 `vite` 的别名，直接把绝对路径改成包名或对应的 `ES Module` 文件。

```js
          match: /\.umi\/umi\.ts/,
          find: "@umijs/renderer-react/dist/index.js",
          replacement: "@umijs/renderer-react",
        },
        {
          match: /\/plugin-dva\/dva\.ts/,
          find: "dva-immer/dist/index.js",
          replacement: "dva-immer/dist/index.esm.js",
        },
```

**Comment by sanyuan0704** [comment]
这样对于当前的依赖可以适用esm产物，但如果间接依赖没有esm格式的产物呢？不就直接报错了吗

**Comment by ltaoo** [comment]
如果没有，`vite` 要求配置在 `optimizeDeps.include` 中，可以强制 `Pre Bundling`，这个时候就会将 `Commonjs` 或 `UMD` 包处理成 `ES Module`。
所以，在 `config/config.ts` 中的 `vite` 配置同样可以使用该配置项

```js
// config/config.ts
  vite: {
    optimizeDeps: {
      include: [
        'react',
        'react-dom',
        'query-string',
        'moment',
        '@umijs/route-utils',
        '@ant-design/pro-layout',
        '@ant-design/icons',
      ],
    },
  },
```

对于一些依赖的依赖，之前 `vite` 会出现处理不了的场景，所以这个插件还额外增加了 `commonjsModules` 配置
```js
// config/config.ts
  commonjsModules: ['warning/warning.js', 'fast-deep-equal/index.js'],
```

上面两个配置在 `example` 项目都有使用。

https://vitejs.dev/config/#optimizedeps-include
https://vitejs.dev/guide/dep-pre-bundling.html#dependency-pre-bundling
