### ISSUE TITLE
如何使用vitePlugins/dayjs.ts？

### ISSUE THREAD

**Issue by li9269391** [ltaoo/umi-preset-vite#4]
它是否可用于antd的moment转dayjs的呢？

**Comment by ltaoo** [comment]
可以的，https://github.com/ltaoo/umi-preset-vite-example  这里更新了示例，里面应用了 `dayjs` 插件，替换了 `antd` 中的 `moment`。

具体配置流程

## 1、增加 vite 插件
在 `umi` 配置文件中的 `vite` 配置增加 `plugins`，注册 `dayjs` 插件
```js
// @ts-ignore
import DayjsPlugin from 'umi-preset-vite/lib/vitePlugins/dayjs';

export default defineConfig({
  vite: {
    plugins: [
      DayjsPlugin({
        plugins: [
          'isSameOrBefore',
          'isSameOrAfter',
          'isToday',
          'isTomorrow',
          'isYesterday',
          'advancedFormat',
          'customParseFormat',
          'weekday',
          'weekYear',
          'weekOfYear',
          'isMoment',
          'localeData',
          'localizedFormat',
          'badMutable',
        ],
      }),
    ],
  },
};
```

## 2、增加 alias 配置将 moment 指向 dayjs
同样是 `umi` 配置文件

```js
export default defineConfig({
  alias: {
    moment: 'dayjs',
  },
});
```

## 3、手动引入 `dayjs` 入口文件
在业务代码的入口文件处

```js
import 'init-dayjs-webpack-plugin-entry.js';
```

原理和 `antd-dayjs-webpack-plugin` 是一样的，即通过别名将 `moment` 引用指向 `dayjs`；增加一个虚拟的入口文件帮助 `dayjs` 注册一些插件，提供 `dayjs` 本身没有但 `moment` 有的方法；

**Comment by ltaoo** [comment]
其实不建议这样做，因为现在 `vite` 和 `webpack` 的插件系统是不兼容的，所有 `webpack2vite` 类方案，都没有解决复用 `webpack` 插件、loader 问题，包括我这个 `umi-preset-vite`，这就导致了存在冗余配置，一份给 `vite` 作开发时使用，一份给 `webpack` 做打包时使用。

好像 `umi` 最新版也支持 `vite` 开发 `webpack` 打包，不知道它有没有解决这个问题。
