### ISSUE TITLE
有关babel运行时的是cjs的问题

### ISSUE THREAD

**Issue by jinphic** [ltaoo/umi-preset-vite#5]
有关babel运行时的是cjs的问题`node_modules/@babel/runtime/regenerator/index.js` 	

```js
module.exports = require("regenerator-runtime");
```

vite 在启动项目的时候，入口文件是 `node_modules/dva-loading/dist/index.esm.js`.
![image](https://user-images.githubusercontent.com/78671853/145143270-389487c0-1674-4b18-9015-7eaef1c5354f.png)
![image](https://user-images.githubusercontent.com/78671853/145143440-b764748c-26f2-4f16-8f23-7d656ba2e187.png)

由于vite是`<script type="module"></script>`的，在浏览器中没有require关键字。所以babel需要做一次转化
![image](https://user-images.githubusercontent.com/78671853/145143644-fee3aaa6-cd0e-4b0e-9d55-58c3721e47df.png)
然后再在进程结束的时候，恢复过来

```ts
const babelRuntimePath = path.resolve('node_modules/@babel/runtime/regenerator/index.js');

async function modifyBabelToCjs() {
  await fs.writeFile(babelRuntimePath, `
    module.exports = require("regenerator-runtime");
  `)
}
  async function onSignal(signal: string) {
    await modifyBabelToCjs();
    destroy();
    api.applyPlugins({
      key: "onExit",
      type: api.ApplyPluginsType.event,
      args: {
        signal,
      },
    });
    process.exit(0);
  }
```

**Comment by jinphic** [comment]
然后再在进程结束的时候，恢复过来

这个原因是最后umi试用webpack 打包构建的时候，使用到babel，不恢复原来的内容打包后的产物不管是大小还是hash都不一样

**Comment by ltaoo** [comment]
确实浏览器处理不了 `require` 方法，所以 `vite` 会在启动开发服务时对依赖进行预处理，最重要的就是将 `CommonJS` 模块转成 `ES Module`。

我看了 `dva-loading/dist/index.esm.js` 源码，问题就是在 `@babel/runtime/regenerator` 这个依赖里面有 `require` 语法对吧，理论上来说这种代码就应该由 `vite` 来处理，如果发现没有被 `vite` 处理（该依赖没有被索引到），可以自己手动指定要处理它

https://vitejs.dev/config/#optimizedeps-include

```js
// .umirc.ts
export default defineConfig({
  vite: {
    optimizeDeps: {
      include: ['@babel/runtime/regenerator'],
    },
  },
});
```

所以不需要我们额外实现插件，不知道能解决你的问题吗

**Comment by jinphic** [comment]
> 确实浏览器处理不了 `require` 方法，所以 `vite` 会在启动开发服务时对依赖进行预处理，最重要的就是将 `CommonJS` 模块转成 `ES Module`。
> 
> 我看了 `dva-loading/dist/index.esm.js` 源码，问题就是在 `@babel/runtime/regenerator` 这个依赖里面有 `require` 语法对吧，理论上来说这种代码就应该由 `vite` 来处理，如果发现没有被 `vite` 处理（该依赖没有被索引到），可以自己手动指定要处理它
> 
> https://vitejs.dev/config/#optimizedeps-include
> 
> ```js
> // .umirc.ts
> export default defineConfig({
>   vite: {
>     optimizeDeps: {
>       include: ['@babel/runtime/regenerator'],
>     },
>   },
> });
> ```
> 
> 所以不需要我们额外实现插件，不知道能解决你的问题吗

这是我vite使用不熟练了，我尝试一下，谢谢大佬指点

**Comment by HelenTim** [comment]
这个问题我居然自己昨天解决了
